name: locate-3d-preprocessing-mast3r
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pillow
  - opencv
  - omegaconf
  - hydra-core
  - wget
  - pip:
      - torch==2.3.1
      - torchvision==0.18.1
      - --index-url https://download.pytorch.org/whl/cu121
  - pip:
      - torch-geometric
      - torch-scatter==2.1.2 -f https://data.pyg.org/whl/torch-2.3.1+cu121.html
      - git+https://github.com/openai/CLIP.git
      - git+https://github.com/facebookresearch/segment-anything.git
      - transformers==4.52.3 